name: "DCX Action"
description: "Install dcx-cli from GitHub Release and run DCX"

inputs:
  dcx_tag:
    description: 'Release tag or "latest"'
    default: "latest"
    required: false

  repo_path:
    description: "Target repo path to scan"
    default: "${{ github.workspace }}"
    required: false
  scanner_dir:
    description: "Folder with Makefile targets (optional)"
    default: "."
    required: false
  max_checks:
    description: "Poll count"
    default: "30"
    required: false
  delay:
    description: "Poll delay seconds"
    default: "1.0"
    required: false

  ai_endpoint:
    description: "Optional AI endpoint"
    required: false
  ai_api_key:
    description: "Optional AI key"
    required: false

  dcx_service_token:
    description: "Token for DCX download service (use secrets)"
    required: True

runs:
  using: "composite"
  steps:
    - name: Run DCX Python bootstrap
      shell: bash
      env:
        DCX_URL: ${{ inputs.dcx_url }}
        DCX_OWNER: ${{ inputs.dcx_owner }}
        DCX_REPO: ${{ inputs.dcx_repo }}
        DCX_TAG: ${{ inputs.dcx_tag }}
        DCX_ASSET_PATTERN: ${{ inputs.dcx_asset_pattern }}
        REPO_PATH: ${{ inputs.repo_path }}
        SCANNER_DIR: ${{ inputs.scanner_dir }}
        MAX_CHECKS: ${{ inputs.max_checks }}
        DELAY: ${{ inputs.delay }}
        AI_ENDPOINT: ${{ inputs.ai_endpoint }}
        AI_API_KEY: ${{ inputs.ai_api_key }}
        DMC_SERVICE_TOKEN: ${{ inputs.dcx_service_token }}
        GITHUB_TOKEN: ${{ github.token }}
      run: python3 "${{ github.action_path }}/dcx.py"
